from app.repositories.exercise_repository import list_exercises, get_exercise
from app.repositories.user_repository import (
    create_user,
    email_exists,
    get_user_by_email,
    get_user_by_id,
    update_last_login,
    user_is_admin,
)
from app.repositories.perfil_salud_repository import create_or_update_perfil, delete_perfil, get_perfil_by_usuario
from app.repositories.rutina_repository import (
    create_rutina,
    delete_rutina,
    get_rutina_by_id,
    get_rutina_for_execute,
    list_rutinas,
    update_rutina,
)
from app.repositories.sesion_repository import (
    create_sesion,
    delete_sesion,
    get_registros_by_sesion,
    get_sesion_by_id,
    list_sesiones,
    registrar_sets,
    update_sesion,
)
from app.repositories.registro_diario_repository import (
    get_registro_by_fecha,
    list_registros,
    upsert_registro_diario,
)
from app.repositories.admin_repository import (
    create_admin_user_legacy as create_admin_user,
    get_stats,
    list_all_users,
    update_admin_user,
    get_admin_ai_settings,
    upsert_admin_ai_settings,
    list_admin_users,
    get_admin_user,
    update_admin_user_token_limit,
    update_admin_user_status,
)
from app.repositories.maquina_gym_repository import (
    create_maquina,
    delete_maquina,
    get_maquina_by_id,
    list_maquinas,
    update_maquina,
)
from app.repositories.plan_semanal_repository import (
    create_plan_semanal,
    deactivate_plan,
    delete_plan_semanal,
    get_plan_by_id,
    list_planes_semanales,
    update_plan_semanal,
)
from app.repositories.user_profile_repository import (
    build_ai_status,
    get_user_profile,
    upsert_user_profile,
)
from app.repositories.workout_session_repository import (
    create_workout_session,
    get_workout_session,
    list_workout_sessions,
)

__all__ = [
    "list_exercises",
    "get_exercise",
    "create_user",
    "email_exists",
    "get_user_by_email",
    "get_user_by_id",
    "update_last_login",
    "user_is_admin",
    "create_or_update_perfil",
    "delete_perfil",
    "get_perfil_by_usuario",
    "create_rutina",
    "delete_rutina",
    "get_rutina_by_id",
    "get_rutina_for_execute",
    "list_rutinas",
    "update_rutina",
    "create_sesion",
    "delete_sesion",
    "get_registros_by_sesion",
    "get_sesion_by_id",
    "list_sesiones",
    "registrar_sets",
    "update_sesion",
    "get_registro_by_fecha",
    "list_registros",
    "upsert_registro_diario",
    "create_admin_user",
    "get_stats",
    "list_all_users",
    "update_admin_user",
    "create_maquina",
    "delete_maquina",
    "get_maquina_by_id",
    "list_maquinas",
    "update_maquina",
    "create_plan_semanal",
    "deactivate_plan",
    "delete_plan_semanal",
    "get_plan_by_id",
    "list_planes_semanales",
    "update_plan_semanal",
    "build_ai_status",
    "get_user_profile",
    "upsert_user_profile",
    "create_workout_session",
    "get_workout_session",
    "list_workout_sessions",
    "get_admin_ai_settings",
    "upsert_admin_ai_settings",
    "list_admin_users",
    "get_admin_user",
    "update_admin_user_token_limit",
    "update_admin_user_status",
]
